### ISSUE TITLE
Issue creating API Products from UI

### ISSUE THREAD

**Issue by asaintsever** [solo-io/istio-dev-portal-issues#1]
**Env**

- Gloo Enterprise Helm chart version: `1.5.0-beta10`
- Gloo Developer Portal Helm chart version: `0.4.8`

**Issue**

Try to create an API Product from the UI: 

- after clicking on the `Create API Product` button the dialog box is never closed. However the `APIProduct` resource is created (check with kubectl)
- click on `Cancel` to get rid of the dialog box then navigate to `API Products`: the created product does not appear in the UI

**Comment by marcogschmidt** [comment]
This should have been solved in the newly released version `0.4.9`.

**Comment by marcogschmidt** [comment]
Confirmed to have been solved with version 0.4.9.
