### ISSUE TITLE
APIProduct CRDs manually deployed do not appear in UI

### ISSUE THREAD

**Issue by asaintsever** [solo-io/istio-dev-portal-issues#2]
**Env**

- Gloo Enterprise Helm chart version: `1.5.0-beta10`
- Gloo Developer Portal Helm chart version: `0.4.8`

**Issue**

Deploy an `APIProduct` resource manually in the cluster then go into Gloo Developer Portal: no product found while its status is successful and virtual service has been created.

**Comment by marcogschmidt** [comment]
This should have been solved in the newly released version 0.4.9.

**Comment by marcogschmidt** [comment]
Confirmed to have been solved with version 0.4.9.
